### ISSUE TITLE
Screen display is messed up while printing. 

### ISSUE THREAD

**Issue by kristophergroves2023** [johncarlson21/SV04-IDEX-3D-Printer-Mainboard-Source-code#11]
On your latest firmware and screen firmware the screen display is messed up while printing leaving you unable to stop or adjust the print.

**Comment by Sr-Loki** [comment]
![20230109_205044.jpg](https://user-images.githubusercontent.com/122329483/211443653-391a9d8c-faa1-4631-becc-c0869eb9f01f.jpg)

Sorry about the bad quality photo 

Flashed to screen 1.2.3 and 1.2.3a
Main board 1.2.3.1b

**Comment by johncarlson21** [comment]
This has been tracked down to loading the same file sized icl images.
The way to fix this is to upload another file renamed or changed just a bit.

**Comment by kristophergroves2023** [comment]
I’m confused on what exactly I need to do

**Comment by johncarlson21** [comment]
Please go to the screen firmware repository and go to the latest release as there are instructions there.

**Comment by johncarlson21** [comment]
This is the release to fix this....
https://github.com/johncarlson21/SV04-Touchscreen/releases/tag/V1.2.3.1pre
