### ISSUE TITLE
Increase speed of extrusion in the "Refuel" screen

### ISSUE THREAD

**Issue by trunzoc** [johncarlson21/SV04-IDEX-3D-Printer-Mainboard-Source-code#12]
Not an issue,  just a request.

Thank you in advance.

**Comment by johncarlson21** [comment]
What would be an extrusion speed you would think is good? it is currently set at 1mm/second.
I don't know if you want to go too fast.

**Comment by trunzoc** [comment]
Hmmm.  I'd at least double it.  I'll try to run some tests and see

**Comment by johncarlson21** [comment]
This has been doubled in the 1.2.4 release.
