### ISSUE TITLE
Cannot Set X-Offset higher than 0.02

### ISSUE THREAD

**Issue by lullaby37** [johncarlson21/SV04-IDEX-3D-Printer-Mainboard-Source-code#14]
Hey,
thanks for your great work and great fork of this code.
I installed it on my SV04 today and when tried to set the X-Offset that I calibrated in the original firmware, I realized that I could not set it higher than 0.02 or lower than -0.02.
It works, however, for Y-Offset like charm.

Any ideas how to fix this?

**Comment by sdevine** [comment]
If you click the text/number, can you add the offset via the on-screen keyboard?  Meaning - the buttons don't increment it but you can still set it?

**Comment by lullaby37** [comment]
Is that possible? I did not know. 
I just always used the +/- .
Unfortunatelly I cannot test this today as it is the printer I use at work, so I can only test it tomorrow.

When I clicked +/- it would go up or down till 0.02/-0.02 and then the screen would just flicker when a bit when pressing it but the number would not change.

I will test typing in the numbers tomorrow. Thanks.

**Comment by johncarlson21** [comment]
> Is that possible? I did not know. I just always used the +/- . Unfortunatelly I cannot test this today as it is the printer I use at work, so I can only test it tomorrow.
> 
> When I clicked +/- it would go up or down till 0.02/-0.02 and then the screen would just flicker when a bit when pressing it but the number would not change.
> 
> I will test typing in the numbers tomorrow. Thanks.

What version of my printer and screen firmware are you using?
We could potentially add a keyboard adjustment, however I worry people will enter in the wrong number and the nozzle will crash
The other issue is there would need to be a calculation to determine the current setting and adjust it.

**Comment by lullaby37** [comment]
So there is no keyboard adjustment then?
I dont need a keyboard, I just need to +/- buttons to work, so no worries about the keyboard.
Sorry for the misunderstanding.

The buttons actually work but the +button only works until the number in the middle reacher 0.02 and the same applies to the - button. Once I reach -0.02 the number is stuck.

I am on the latest version of your firmware btw.

**Comment by johncarlson21** [comment]
That is odd. Mine works just fine and I am way down at -2.07

![image](https://user-images.githubusercontent.com/25893/212236503-18fa5f69-f54a-4d02-81aa-817b024c8fc0.jpeg)

**Comment by sdevine** [comment]
That's the z offset.  I think we are talking about the extruder 2 offsets

**Comment by lullaby37** [comment]
Indeed, Z-offset works flawlessley. The X-Offset is the problem, the Y-Offset is fine.

**Comment by lullaby37** [comment]
Typing in the correct value solves the problem. Also, once it's typed in and saved, I can use +/- to increase and decrease as much as i want.
Thanks for your help!
